language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - TOXENV=py34-17
  - TOXENV=py34-18
  - TOXENV=py34-19
  - TOXENV=py35-18
  - TOXENV=py35-19
  - TOXENV=py27-17
  - TOXENV=py27-18
  - TOXENV=py27-19

branches:
    only:
        - master

install: pip install --quiet tox

# command to run tests
script: tox

after_script:
    - if [ $TOXENV == "py27-19" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
